title: "Damienne's Retro Games, Tech, and More!"
description: "Listen to me review retro games, rant on random topics, and more!"
author:
  name: "Damienne B."
  email: "damianbabs2008@gmail.com"
  url: "https://www.damian-is-silly.xyz/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Damienne"
year : "2024"
